# [START django_app]
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /static
  static_dir: static/
- url: .*
  script: mysite.wsgi.application


libraries:
- name: MySQLdb
  version: 1.2.5
# [END django_app]



skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^env/.*$
