# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-04 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
