# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-04 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcare', '0002_message_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('domain', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
