# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-06 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcare', '0003_auto_20180105_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='firstname',
            new_name='firs_tname',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
