# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-06 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcare', '0004_auto_20180106_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='firs_tname',
            new_name='first_name',
        ),
    ]
