# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-06 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcare', '0005_auto_20180106_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='doc',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='sender',
        ),
    ]
